Implement Training package
a-nych/CapWSB-FitnessTracker pull request #4
Opened 2024-11-13 17:23 UTC by a-nych

2024-11-15 12:09 UTC, Sharrat requested changes

2024-11-15 12:09 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingMapper.java
> +        User user = userProvider.getUser(dto.getUserId())
Id of the training record is auto incremental, we shouldnt have to include it in the create DTO because it will set itself when creating. Also even if we do include it why check if a record exists with a "new" id and throw exception if it doesnt when we are creating it after :D

2024-11-15 12:09 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingMapper.java
> +    Training toUpdatedEntity(Training existingTraining, TrainingCreateDto dto) {
Updated entity should have its own dto since it differs from create dto because it includes id of the record we are updating -> check user solution for reference

2024-11-15 12:11 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/api/TrainingProvider.java
> +     * @param userId ID of the user
sus

2024-11-17 23:29 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingDto.java
> +    private Long userId;
Currently this is always null when getting trainings

2024-11-17 23:31 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/user/internal/UserDetailsDto.java
Why does this exist, you already have user DTO from previous lab

2024-11-17 23:45 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingRepository.java
> +    default List<Training> findByActivityType(ActivityType activityType) {
Maybe should be made case insensitive?

2024-11-17 23:59 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingController.java
> +    @PutMapping("/{trainingId}")
Update doesnt work correctly, fields need to made nullable so it doesnt require to provide all the information even when trying to change only 1 field for example.

2024-11-18 00:00 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingController.java
> +    @PutMapping("/{trainingId}")
![image](https://github.com/user-attachments/assets/1d88f48f-10d3-4e43-9e7b-9ac7b5931b58)

2024-11-18 00:01 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingDto.java
> +    private Long userId;
![image](https://github.com/user-attachments/assets/693e17c1-258b-4fac-9376-cedfc804473d)

2024-11-18 00:02 UTC, Sharrat commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/internal/TrainingController.java
> +    @PutMapping("/{trainingId}")
thats why update should have its own DTO

2024-11-20 17:44 UTC, a-nych commented on src/main/java/com/capgemini/wsb/fitnesstracker/training/api/TrainingProvider.java
> +     * @param userId ID of the user
Can you elaborate?

2024-11-20 21:40 UTC, Sharrat approved these changes

2024-11-20 21:41 UTC, Sharrat approved these changes

2024-11-20 21:41 UTC, merged